import { useGLTF, useKeyboardControls, PerspectiveCamera } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useRef } from "react";
import { Vector3 } from "three";
import { LEVEL_SIZE } from "../utils/constants";
import { mutation } from "../utils/stores";

const R = 0.2;
const THETA = Math.PI / 10;

export function Ship() {
    const container = useRef();
    const ship = useRef();
    const [, getKeys] = useKeyboardControls();

    const velocity = useRef(new Vector3(0, 0, -10));
    // const boostSpeed = useRef(10)

    useFrame(({ clock }, delta) => {
        const { up, down, left, right, boost } = getKeys();

        const time = clock.getElapsedTime();
        const slowSine = Math.sin(time );

        mutation.level = Math.abs(Math.floor(container.current.position.z / LEVEL_SIZE)) - 1;

        // if (up) velocity.x += ;
        // if (down) shipRef.current.translateY(-speed);
        // if (left) shipRef.current.translateX(-speed);
        // if (right) shipRef.current.translateX(speed);
        if (boost) {
            container.current.position.z += velocity.current.z * 100 * delta;
        } else {
            container.current.position.z += velocity.current.z * 10 * delta;
        }

        // container.position.copy(pos.current)
        // ship.current.position.y -= slowSine/200;
    });

    return (
        <group>
            <group ref={container}>
                <PerspectiveCamera
                    makeDefault
                    far={8000}
                    position-z={R * Math.cos(THETA)}
                    position-y={R * Math.sin(THETA)}
                />
                <group ref={ship}>
                    <ShipModel rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.01} />
                </group>
            </group>
        </group>
    );
}

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sergio Sotomayor (https://sketchfab.com/sergiosotomayor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toon-spaceship-ce3e358791a84ebc8c9c36f71ce3e603
Title: Toon Spaceship
*/

function ShipModel({ ...props }) {
    const { nodes } = useGLTF("models/spaceship/scene.gltf");

    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Spaceship_fuselage_0.geometry}>
                <meshStandardMaterial color={"#121212"} />
            </mesh>
            <mesh geometry={nodes.Spaceship_frames_0.geometry}>
                <meshStandardMaterial color={"black"} />
            </mesh>
            <mesh geometry={nodes.Spaceship_paint_0.geometry}>
                <meshStandardMaterial color={"black"} />
            </mesh>
            <mesh geometry={nodes.Spaceship_motors_0.geometry}>
                <meshBasicMaterial color={"black"} />
            </mesh>
        </group>
    );
}

useGLTF.preload("models/spaceship/scene.gltf");
