/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sergio Sotomayor (https://sketchfab.com/sergiosotomayor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toon-spaceship-ce3e358791a84ebc8c9c36f71ce3e603
Title: Toon Spaceship
*/

import { useGLTF } from '@react-three/drei'

export function Ship(props) {
  const { nodes, materials } = useGLTF('/models/spaceship/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.063, 6.214, -26.641]} rotation={[-Math.PI / 2, 0, 0]} scale={1}>
        <mesh geometry={nodes.Spaceship_fuselage_0.geometry} material={materials.fuselage} />
        <mesh geometry={nodes.Spaceship_frames_0.geometry} material={materials.frames} />
        <mesh geometry={nodes.Spaceship_glass_0.geometry} material={materials.glass} />
        <mesh geometry={nodes.Spaceship_paint_0.geometry} material={materials.paint} />
        <mesh geometry={nodes.Spaceship_motors_0.geometry} material={materials.motors} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/spaceship/scene.gltf')
